name: Compile & Publish Design System Assets

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      packages: write 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          token: ${{ secrets.GITHUB_TOKEN }} 
      
      - name: Initialize Runtime Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: '@radheshyam-dangi' 

      - name: Synchronize Dependencies
        run: npm ci

      - name: Trigger Component Production Compile Build
        run: npm run build

      - name: Configure Git User
        run: |
          git config --global user.name "radheshyam-dangi"
          git config --global user.email "radheshyam.dangi@infoobjects.com"

      - name: Automatically Bump Package Version
        # [skip ci] se GitHub Actions samajh jayega ki dubara workflow nahi chalana hai
        run: npm version patch -m "chore(release): bump version to %s [skip ci]"

      - name: Distribute Assets Registry Target Authorization
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Version Update Back to Repository
        # Sahi tarika tags aur code dono ko ek sath wapas bhejne ka
        run: git push origin main --follow-tags